// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsesiafkxstjhypiicsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZXNpYWZreHN0amh5cGlpY3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTU1MDgsImV4cCI6MjA2OTM5MTUwOH0.ZuoPjr2u0N6izh_Ysg9C4H9Q1S52a1ztBuuAWUA0Ou8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});